version: '3.8'

name: norubanner

x-common-options: &common-options
  restart: "no"

services:
  db:
    <<: *common-options
    image: postgres:16
    container_name: norubanner_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: NoruBannerDb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - norubanner_network
  norubanner.webapi:
    <<: *common-options
    image: ${DOCKER_REGISTRY-}norubannerwebapi
    container_name: norubanner_api
    build:
      context: .
      dockerfile: NoruBanner.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__Default=Host=db;Port=5432;Database=NoruBannerDb;Username=postgres;Password=123456
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - norubanner_network
  norubanner.client:
    <<: *common-options
    build:
      context: ../../Client
      dockerfile: Dockerfile
    container_name: norubanner_client
    ports:
      - "80:80"
    depends_on:
      - norubanner.webapi
    networks:
      - norubanner_network

volumes:
  postgres_data:
    name: norubanner_postgres_data

networks:
  norubanner_network:
    driver: bridge
    attachable: true
    labels:
      - "com.docker.compose.project=norubanner"